
<body>
  <div class="container-fluid most">
    <div class="row">
      <div class="col-md-6 popular">
        <div class="col-md-12 mostpopular">
          <div class="row first">
             <div class="col-md-12 pagetitle">
                <h1 class="popularhead">MOST POPULAR IN STORE</h1>
             </div>
            <div class="col-md-3 pro first">
              <div class="productmost">
                  <div class="productpop">
                    <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/1.png'); ?>" class="img-product" alt="">
                  </div>
                  <div class="productcont-content">
                    <h5 class="mosthead">Aliquam Placerat</h5>
                    <p class="pro-price"><strike>$400.00</strike> <span class="price-or">$369.00</span></p>
                  </div>
              </div>
            </div>
            <div class="col-md-3 pro first">
              <div class="productmost">
                  <div class="productpop">
                    <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/22_1.png'); ?>" class="img-product" alt="">
                  </div>
                  <div class="productcont-content">
                    <h5 class="mosthead">Aliquam Placerat</h5>
                    <p class="pro-price"><span class="price-or">$369.00</span></p>
                  </div>
              </div>
            </div>
            <div class="col-md-3 pro">
              <div class="productmost">
                  <div class="productpop">
                    <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/11.png'); ?>" class="img-product" alt="">
                  </div>
                  <div class="productcont-content">
                    <h5 class="mosthead">Aliquam Placerat</h5>
                    <p class="pro-price"> <span class="price-or">$369.00</span></p>
                  </div>
              </div>
            </div>
            <div class="col-md-3 pro">
              <div class="productmost">
                  <div class="productpop">
                    <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/10_1 (1).png'); ?>" class="img-product" alt="">
                  </div>
                  <div class="productcont-content">
                    <h5 class="mosthead">Aliquam Placerat</h5>
                    <p class="pro-price"><strike>$400.00</strike> <span class="price-or">$369.00</span></p>
                  </div>
              </div>
            </div>
          </div>
          <div class="row first">
              <div class="col-md-12 pagetitle">
                <h1 class="popularhead">BEST SELLER PRODUCTS</h1>
              </div>
            <div class="col-md-3 pro first">
              <div class="productmost">
                  <div class="productpop">
                    <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/1.png'); ?>" class="img-product" alt="">
                  </div>
                  <div class="productcont-content">
                    <h5 class="mosthead">Aliquam Placerat</h5>
                    <p class="pro-price"><strike>$400.00</strike> <span class="price-or">$369.00</span></p>
                  </div>
              </div>
            </div>
            <div class="col-md-3 pro first">
              <div class="productmost">
                  <div class="productpop">
                    <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/44.png'); ?>" class="img-product" alt="">
                  </div>
                  <div class="productcont-content">
                    <h5 class="mosthead">Aliquam Placerat</h5>
                    <p class="pro-price"><span class="price-or">$369.00</span></p>
                  </div>
              </div>
            </div>
            <div class="col-md-3 pro">
              <div class="productmost">
                  <div class="productpop">
                    <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/7-2 (1).png'); ?>" class="img-product" alt="">
                  </div>
                  <div class="productcont-content">
                    <h5 class="mosthead">Aliquam Placerat</h5>
                    <p class="pro-price"> <span class="price-or">$369.00</span></p>
                  </div>
              </div>
            </div>
            <div class="col-md-3 pro">
              <div class="productmost">
                  <div class="productpop">
                    <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/33.png'); ?>" class="img-product" alt="">
                  </div>
                  <div class="productcont-content">
                    <h5 class="mosthead">Aliquam Placerat</h5>
                    <p class="pro-price"><strike>$400.00</strike> <span class="price-or">$369.00</span></p>
                  </div>
              </div>
            </div>
          </div>
          </div>
        </div>
      <div class="col-md-6 dealofthe">
         <div class="row">
            <div class="col-md-6 deal">
              <h1 class="dealhead">DEAL OF THE DAYS</h1>
            </div>
             <div class="col-md-6 dealbanner">
              <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/banner02.jpg'); ?>" class="banner">
            </div>
          </div>
      </div>
    </div>
  </div> 